### ISSUE TITLE
Any documentation on using this gem in a script/rake task?

### ISSUE THREAD

**Issue by kenman345** [bkuhlmann/flacsmith#1]
Was wondering if this gem could be used in a ruby script and not just command line.

**Comment by bkuhlmann** [comment]
Yep, it definitely can. The CLI is mostly a convenience wrapper for the underlining implementation. For example, if you wanted to write a Ruby script that used the album converter, you might do something like this:

```
converter = Converters::Album.new input_dir: <input dir>,
                                  output_dir: <output dir>,
                                  picture_path: <path to album cover>
converter.convert
```

Album and track converters can be found in the [converters folder](https://github.com/bkuhlmann/flacsmith/tree/master/lib/flacsmith/converters). Objects for dealing with metadata can be found in the [metadata folder](https://github.com/bkuhlmann/flacsmith/tree/master/lib/flacsmith/metadata).

You can use the [CLI class](https://github.com/bkuhlmann/flacsmith/blob/master/lib/flacsmith/cli.rb) as an entry point to getting started since everything begins there.
